FROM openjdk:8-jdk-alpine
EXPOSE 8080
COPY target/spring-boot-react-mysql-0.0.1-SNAPSHOT.jar spring-boot-react-mysql-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/spring-boot-react-mysql-0.0.1-SNAPSHOT.jar"]